        
httpserver.alloworigin = .*
httpserver.userfile = conf/users.dat
httpserver.groupfile = conf/groups
httpserver.passwdfile = conf/passwd
httpserver.keyfile = conf/peers
httpserver.loginkeyfile = conf/logins.dat
cacert.keystore = conf/polaric-ca.p12
cacert.alias = polaric-root-ca

# Password for the keystore
cacert.keystore.pw = xxxxxxx

# Set your issuer DN her
cacert.issuer = CN=My Root CA

# Logging of certificate signing
cacert.log.file = logs/ca.log
cacert.log.on = true
