

# Password for the keystore
cacert.keystore.pw = xxxxxxx

# Set your issuer DN here
cacert.issuer = CN=My Root CA

# Logging of certificate signing
cacert.log.on = true


#
# You shouldn't normally edit these
#
        
httpserver.alloworigin = .*
httpserver.keyfile = /etc/polaric-certauth/peers
cacert.keystore = /var/lib/polaric/certauth/polaric-ca.p12
cacert.alias = polaric-root-ca
cacert.log.file = /var/log/polaric/certauth.log

#
# These are not used
# Is it safe to remove them? 
#

httpserver.userfile = /etc/polaric-certauth/users.dat
httpserver.groupfile = /etc/polaric-certauth/groups
httpserver.passwdfile = /etc/polaric-certauth/passwd
httpserver.loginkeyfile = /var/lib/polaric/certauth/logins.dat
