# Base URL of the Polaric-Certauth service
service_url = https://aprs.no/ca

# Service paths
sign_path = /cacert/sign

# User id (service-id)
userid = arctic

# Authentication secret
# shared_secret: static service/device secret from the server key file
shared_secret = xxxx

# Validity (default is 768)
# days = 365
