# Base URL of the Polaric-Certauth service
service_url = https://aprs.no/ca

# Service paths
sign_path = /cacert/sign

# Input and output files
csr_file = csr.pem
cert_file = certificate.pem

# User id (service-id)
userid = arctic

# Authentication secret
# shared_secret: static service/device secret from the server key file
shared_secret = xxxx

# Validity (default is 365)
# days = 365
