#!/bin/bash
set -e
INIFILE=/etc/polaric-aprsd/server.ini


case "$1" in

    configure|reconfigure)
        if [ "$1" == "configure" ] ; then
           chown polaric:polaric /var/lib/polaric/certauth
           chmod 700 /var/lib/polaric/certauth
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
